export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13.0.4";
  };
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          nickname: string | null;
          avatar_url: string | null;
          subscription_tier: string | null;
          remaining_minutes: number | null;
          current_level: number | null;
          crystal_balance: number | null;
          daily_streak: number | null;
          last_streak_date: string | null;
          role: string;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email: string;
          nickname?: string | null;
          avatar_url?: string | null;
          subscription_tier?: string | null;
          remaining_minutes?: number | null;
          current_level?: number | null;
          crystal_balance?: number | null;
          daily_streak?: number | null;
          last_streak_date?: string | null;
          role?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string;
          nickname?: string | null;
          avatar_url?: string | null;
          subscription_tier?: string | null;
          remaining_minutes?: number | null;
          current_level?: number | null;
          crystal_balance?: number | null;
          daily_streak?: number | null;
          last_streak_date?: string | null;
          role?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      level_thresholds: {
        Row: {
          id: string;
          level: number;
          crystals_required: number;
          title: string | null;
          description: string | null;
          rewards: Json | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          level: number;
          crystals_required: number;
          title?: string | null;
          description?: string | null;
          rewards?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          level?: number;
          crystals_required?: number;
          title?: string | null;
          description?: string | null;
          rewards?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      assessments_enhanced: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          type: string;
          category: string;
          difficulty_level: string | null;
          time_limit_minutes: number | null;
          max_attempts: number | null;
          is_public: boolean | null;
          is_active: boolean | null;
          ai_config_id: string | null;
          questions: Json;
          scoring_rubric: Json | null;
          passing_score: number | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          type: string;
          category: string;
          difficulty_level?: string | null;
          time_limit_minutes?: number | null;
          max_attempts?: number | null;
          is_public?: boolean | null;
          is_active?: boolean | null;
          ai_config_id?: string | null;
          questions: Json;
          scoring_rubric?: Json | null;
          passing_score?: number | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          type?: string;
          category?: string;
          difficulty_level?: string | null;
          time_limit_minutes?: number | null;
          max_attempts?: number | null;
          is_public?: boolean | null;
          is_active?: boolean | null;
          ai_config_id?: string | null;
          questions?: Json;
          scoring_rubric?: Json | null;
          passing_score?: number | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      assessment_attempts: {
        Row: {
          id: string;
          assessment_id: string | null;
          user_id: string | null;
          attempt_number: number;
          started_at: string | null;
          completed_at: string | null;
          time_spent_minutes: number | null;
          status: string | null;
          raw_responses: Json;
          ai_analysis: Json | null;
          ai_score: number | null;
          ai_feedback: string | null;
          is_ai_processed: boolean | null;
          ai_processing_error: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          assessment_id?: string | null;
          user_id?: string | null;
          attempt_number: number;
          started_at?: string | null;
          completed_at?: string | null;
          time_spent_minutes?: number | null;
          status?: string | null;
          raw_responses: Json;
          ai_analysis?: Json | null;
          ai_score?: number | null;
          ai_feedback?: string | null;
          is_ai_processed?: boolean | null;
          ai_processing_error?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          assessment_id?: string | null;
          user_id?: string | null;
          attempt_number?: number;
          started_at?: string | null;
          completed_at?: string | null;
          time_spent_minutes?: number | null;
          status?: string | null;
          raw_responses?: Json;
          ai_analysis?: Json | null;
          ai_score?: number | null;
          ai_feedback?: string | null;
          is_ai_processed?: boolean | null;
          ai_processing_error?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ai_configurations: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          provider: string;
          provider_name: string | null;
          model_name: string;
          api_base_url: string | null;
          api_key_encrypted: string | null;
          api_version: string | null;
          temperature: number | null;
          max_tokens: number | null;
          top_p: number | null;
          frequency_penalty: number | null;
          presence_penalty: number | null;
          stop_sequences: string[] | null;
          custom_headers: Json | null;
          cost_per_1k_prompt_tokens: number | null;
          cost_per_1k_completion_tokens: number | null;
          max_requests_per_minute: number | null;
          max_tokens_per_minute: number | null;
          system_prompt: string | null;
          user_prompt_template: string | null;
          tags: string[] | null;
          metadata: Json | null;
          is_active: boolean | null;
          is_default: boolean | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: string | null;
          last_tested_at: string | null;
          test_status: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          provider: string;
          provider_name?: string | null;
          model_name: string;
          api_base_url?: string | null;
          api_key_encrypted?: string | null;
          api_version?: string | null;
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          frequency_penalty?: number | null;
          presence_penalty?: number | null;
          stop_sequences?: string[] | null;
          custom_headers?: Json | null;
          cost_per_1k_prompt_tokens?: number | null;
          cost_per_1k_completion_tokens?: number | null;
          max_requests_per_minute?: number | null;
          max_tokens_per_minute?: number | null;
          system_prompt?: string | null;
          user_prompt_template?: string | null;
          tags?: string[] | null;
          metadata?: Json | null;
          is_active?: boolean | null;
          is_default?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: string | null;
          last_tested_at?: string | null;
          test_status?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          provider?: string;
          provider_name?: string | null;
          model_name?: string;
          api_base_url?: string | null;
          api_key_encrypted?: string | null;
          api_version?: string | null;
          temperature?: number | null;
          max_tokens?: number | null;
          top_p?: number | null;
          frequency_penalty?: number | null;
          presence_penalty?: number | null;
          stop_sequences?: string[] | null;
          custom_headers?: Json | null;
          cost_per_1k_prompt_tokens?: number | null;
          cost_per_1k_completion_tokens?: number | null;
          max_requests_per_minute?: number | null;
          max_tokens_per_minute?: number | null;
          system_prompt?: string | null;
          user_prompt_template?: string | null;
          tags?: string[] | null;
          metadata?: Json | null;
          is_active?: boolean | null;
          is_default?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: string | null;
          last_tested_at?: string | null;
          test_status?: string | null;
        };
        Relationships: [];
      };
      newme_conversations: {
        Row: {
          id: string;
          user_id: string;
          started_at: string;
          ended_at: string | null;
          duration_seconds: number | null;
          message_count: number;
          topics_discussed: string[] | null;
          emotional_tone: string | null;
          suggested_assessments: string[] | null;
          key_insights: string[] | null;
          summary: string | null;
          metadata: Json | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          started_at?: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          message_count?: number;
          topics_discussed?: string[] | null;
          emotional_tone?: string | null;
          suggested_assessments?: string[] | null;
          key_insights?: string[] | null;
          summary?: string | null;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          started_at?: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          message_count?: number;
          topics_discussed?: string[] | null;
          emotional_tone?: string | null;
          suggested_assessments?: string[] | null;
          key_insights?: string[] | null;
          summary?: string | null;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      newme_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: string;
          content: string;
          timestamp: string;
          audio_duration_ms: number | null;
          sentiment_score: number | null;
          emotion_detected: string | null;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: string;
          content: string;
          timestamp?: string;
          audio_duration_ms?: number | null;
          sentiment_score?: number | null;
          emotion_detected?: string | null;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: string;
          content?: string;
          timestamp?: string;
          audio_duration_ms?: number | null;
          sentiment_score?: number | null;
          emotion_detected?: string | null;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      newme_user_memories: {
        Row: {
          id: string;
          user_id: string;
          memory_type: string;
          memory_key: string;
          memory_value: string;
          context: string | null;
          importance_score: number;
          first_mentioned_at: string;
          last_referenced_at: string;
          reference_count: number;
          source_conversation_id: string | null;
          is_active: boolean;
          metadata: Json | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          memory_type: string;
          memory_key: string;
          memory_value: string;
          context?: string | null;
          importance_score?: number;
          first_mentioned_at?: string;
          last_referenced_at?: string;
          reference_count?: number;
          source_conversation_id?: string | null;
          is_active?: boolean;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          memory_type?: string;
          memory_key?: string;
          memory_value?: string;
          context?: string | null;
          importance_score?: number;
          first_mentioned_at?: string;
          last_referenced_at?: string;
          reference_count?: number;
          source_conversation_id?: string | null;
          is_active?: boolean;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      newme_emotional_snapshots: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string | null;
          snapshot_date: string;
          primary_emotion: string;
          emotion_intensity: number;
          triggers: string[] | null;
          coping_strategies: string[] | null;
          notes: string | null;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id?: string | null;
          snapshot_date: string;
          primary_emotion: string;
          emotion_intensity: number;
          triggers?: string[] | null;
          coping_strategies?: string[] | null;
          notes?: string | null;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string | null;
          snapshot_date?: string;
          primary_emotion?: string;
          emotion_intensity?: number;
          triggers?: string[] | null;
          coping_strategies?: string[] | null;
          notes?: string | null;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      newme_assessment_tracking: {
        Row: {
          id: string;
          user_id: string;
          assessment_name: string;
          suggested_in_conversation_id: string | null;
          suggested_at: string | null;
          completed_at: string | null;
          completion_status: string;
          key_insights: string[] | null;
          follow_up_discussed: boolean;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          assessment_name: string;
          suggested_in_conversation_id?: string | null;
          suggested_at?: string | null;
          completed_at?: string | null;
          completion_status: string;
          key_insights?: string[] | null;
          follow_up_discussed: boolean;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          assessment_name?: string;
          suggested_in_conversation_id?: string | null;
          suggested_at?: string | null;
          completed_at?: string | null;
          completion_status?: string;
          key_insights?: string[] | null;
          follow_up_discussed?: boolean;
          metadata?: Json | null;
        };
        Relationships: [];
      };
      // Add other tables as needed
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};