import type { Json } from "../types";

export type AIConfigurations = {
  Row: {
    id: string;
    name: string;
    description: string | null;
    provider: string;
    provider_name: string | null;
    model_name: string;
    api_base_url: string | null;
    api_key_encrypted: string | null;
    api_version: string | null;
    temperature: number | null;
    max_tokens: number | null;
    top_p: number | null;
    frequency_penalty: number | null;
    presence_penalty: number | null;
    system_prompt: string | null;
    is_default: boolean;
    custom_headers: Json | null;
    cost_per_1k_prompt_tokens: number | null;
    cost_per_1k_completion_tokens: number | null;
    created_at: string;
    updated_at: string;
    test_status: string | null;
    last_tested: string | null;
    is_active: boolean | null;
    user_prompt_template: string | null; // Added missing column
    created_by: string | null; // Added missing column
  };
  Insert: {
    id?: string;
    name: string;
    description?: string | null;
    provider: string;
    provider_name?: string | null;
    model_name: string;
    api_base_url?: string | null;
    api_key_encrypted?: string | null;
    api_version?: string | null;
    temperature?: number | null;
    max_tokens?: number | null;
    top_p?: number | null;
    frequency_penalty?: number | null;
    presence_penalty?: number | null;
    system_prompt?: string | null;
    is_default?: boolean;
    custom_headers?: Json | null;
    cost_per_1k_prompt_tokens?: number | null;
    cost_per_1k_completion_tokens?: number | null;
    created_at?: string;
    updated_at?: string;
    test_status?: string | null;
    last_tested?: string | null;
    is_active?: boolean | null;
    user_prompt_template?: string | null;
    created_by?: string | null;
  };
  Update: {
    id?: string;
    name?: string;
    description?: string | null;
    provider?: string;
    provider_name?: string | null;
    model_name?: string;
    api_base_url?: string | null;
    api_key_encrypted?: string | null;
    api_version?: string | null;
    temperature?: number | null;
    max_tokens?: number | null;
    top_p?: number | null;
    frequency_penalty?: number | null;
    presence_penalty?: number | null;
    system_prompt?: string | null;
    is_default?: boolean;
    custom_headers?: Json | null;
    cost_per_1k_prompt_tokens?: number | null;
    cost_per_1k_completion_tokens?: number | null;
    created_at?: string;
    updated_at?: string;
    test_status?: string | null;
    last_tested?: string | null;
    is_active?: boolean | null;
    user_prompt_template?: string | null;
    created_by?: string | null;
  };
  Relationships: [];
};