export type AssessmentsEnhanced = {
  Row: {
    id: string;
    title: string;
    description: string | null;
    type: string;
    category: string;
    difficulty_level: string | null;
    time_limit_minutes: number | null;
    max_attempts: number | null;
    is_public: boolean | null;
    is_active: boolean | null;
    ai_config_id: string | null;
    questions: import('../types').Json;
    scoring_rubric: import('../types').Json | null;
    passing_score: number | null;
    created_by: string | null;
    created_at: string | null;
    updated_at: string | null;
  };
  Insert: {
    id?: string;
    title: string;
    description?: string | null;
    type: string;
    category: string;
    difficulty_level?: string | null;
    time_limit_minutes?: number | null;
    max_attempts?: number | null;
    is_public?: boolean | null;
    is_active?: boolean | null;
    ai_config_id?: string | null;
    questions: import('../types').Json;
    scoring_rubric?: import('../types').Json | null;
    passing_score?: number | null;
    created_by?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  };
  Update: {
    id?: string;
    title?: string;
    description?: string | null;
    type?: string;
    category?: string;
    difficulty_level?: string | null;
    time_limit_minutes?: number | null;
    max_attempts?: number | null;
    is_public?: boolean | null;
    is_active?: boolean | null;
    ai_config_id?: string | null;
    questions?: import('../types').Json;
    scoring_rubric?: import('../types').Json | null;
    passing_score?: number | null;
    created_by?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  };
  Relationships: [];
};