export type UserProfiles = {
  Row: {
    id: string;
    user_id: string | null;
    email: string;
    nickname: string | null;
    frontend_name: string | null;
    avatar_url: string | null;
    subscription_tier: string | null;
    remaining_minutes: number | null;
    current_level: number | null;
    crystal_balance: number | null;
    daily_streak: number | null;
    last_streak_date: string | null;
    created_at: string | null;
    role: string;
    updated_at: string | null;
  };
  Insert: {
    id?: string;
    user_id?: string | null;
    email: string;
    nickname?: string | null;
    frontend_name?: string | null;
    avatar_url?: string | null;
    subscription_tier?: string | null;
    remaining_minutes?: number | null;
    current_level?: number | null;
    crystal_balance?: number | null;
    daily_streak?: number | null;
    last_streak_date?: string | null;
    created_at?: string | null;
    role?: string;
    updated_at?: string | null;
  };
  Update: {
    id?: string;
    user_id?: string | null;
    email?: string;
    nickname?: string | null;
    frontend_name?: string | null;
    avatar_url?: string | null;
    subscription_tier?: string | null;
    remaining_minutes?: number | null;
    current_level?: number | null;
    crystal_balance?: number | null;
    daily_streak?: number | null;
    last_streak_date?: string | null;
    created_at?: string | null;
    role?: string;
    updated_at?: string | null;
  };
  Relationships: [];
};