export type WellnessResources = {
  Row: {
    id: string;
    title: string;
    category: string;
    duration: number | null;
    audio_url: string | null;
    description: string | null;
    created_at: string | null;
    transcript: string | null;
    is_downloadable: boolean | null;
    download_url: string | null;
    is_premium: boolean | null;
    required_tier: string | null;
    tags: string[] | null;
    usage_count: number | null;
    status: string | null;
    created_by: string | null;
    updated_at: string;
  };
  Insert: {
    id?: string;
    title: string;
    category: string;
    duration?: number | null;
    audio_url?: string | null;
    description?: string | null;
    created_at?: string | null;
    transcript?: string | null;
    is_downloadable?: boolean | null;
    download_url?: string | null;
    is_premium?: boolean | null;
    required_tier?: string | null;
    tags?: string[] | null;
    usage_count?: number | null;
    status?: string | null;
    created_by?: string | null;
    updated_at?: string;
  };
  Update: {
    id?: string;
    title?: string;
    category?: string;
    duration?: number | null;
    audio_url?: string | null;
    description?: string | null;
    created_at?: string | null;
    transcript?: string | null;
    is_downloadable?: boolean | null;
    download_url?: string | null;
    is_premium?: boolean | null;
    required_tier?: string | null;
    tags?: string[] | null;
    usage_count?: number | null;
    status?: string | null;
    created_by?: string | null;
    updated_at?: string;
  };
  Relationships: [];
};